version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: true
    config:
      threshold: 10
  file-lines:
    enabled: true
    config:
      threshold: 1500
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 25
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
 phpcodesniffer:
  enabled: true
 csslint:
  enabled: true
 phpmd:
  enabled: true
 sass-lint:
  enabled: true
 stylelint:
  enabled: true
 tslint:
  enabled: true
  config: tslint.json
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/vendor/"
- "**/*.d.ts"
