language: php

php:
  - 5.6
  - hhvm

env:
  global:
    - setup=basic
    - coverage=false

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable
    - php: 7.0
      env: coverage=true

sudo: false

services:
  - redis-server

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - if [[ $coverage = 'false' ]]; then vendor/bin/phpunit; fi
  - if [[ $coverage = 'true' ]]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml; fi

after_success:
  - if [[ $coverage != 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
