language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest

sudo: false

before_script:
	- composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script: vendor/bin/phpunit
