language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit -d memory_limit=1024M --coverage-clover build/logs/clover.xml

after_script: php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
