version: '3'
services:


  laravel:
    build:
      context: ./
      dockerfile: ./docker/DockerFile
    # awk-landmark (do not remove) #
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/html/src/
      - ./tests/:/var/www/html/tests/
      - ./types/:/var/www/html/types/
      - ./vendor/:/var/www/html/vendor/
      - ./CHANGELOG.md:/var/www/html/CHANGELOG.md
      - ./LICENSE.md:/var/www/html/LICENSE.md
      - ./README.md:/var/www/html/README.md
      - ./.styleci.yml:/var/www/html/.styleci.yml
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist
      - ./phpstan.src.neon.dist:/var/www/html/phpstan.src.neon.dist
      - ./phpstan.types.neon.dist:/var/www/html/phpstan.types.neon.dist
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    restart: always
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "forge"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    restart: always
