name: Bug Report
description: "Report something that's broken."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "[Please ensure your Laravel version is still supported.](https://laravel.com/docs/releases#support-policy)"
  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      description: Please provide the full Laravel version you're using.
      placeholder: 10.4.1
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Please provide the full PHP version you're using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: input
    id: database-version
    attributes:
      label: Database Driver & Version
      description: If applicable, please provide the database driver and full version you're using.
      placeholder: "mysql Ver 8.0.31 for macos13.0 on arm64 (Homebrew)"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the issue you're facing. Don't write a book but provide enough details for us.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue. If possible, please provide a GitHub repository to demonstrate your issue using `laravel new bug-report --github="--public"`.
    validations:
      required: true
      
