name: close-pull-requests

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  close_pull_requests:
    runs-on: ubuntu-20.04

    name: Close all illuminate pull-requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the script
        run: ./bin/close-pull-requests.sh
